# Generated by Django 3.0.7 on 2020-10-11 13:13

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("ulmg", "0001_initial"),
        ("ulmg", "0002_remove_playernote_author"),
        ("ulmg", "0003_auto_20180202_1009"),
        ("ulmg", "0004_auto_20180202_1010"),
        ("ulmg", "0005_auto_20180202_1012"),
        ("ulmg", "0006_player_level"),
        ("ulmg", "0007_auto_20180202_1037"),
        ("ulmg", "0008_auto_20180202_1040"),
        ("ulmg", "0009_auto_20180202_1041"),
        ("ulmg", "0010_auto_20180202_1225"),
        ("ulmg", "0011_auto_20181006_1551"),
        ("ulmg", "0012_remove_player_roster_conflict"),
        ("ulmg", "0013_auto_20181006_2130"),
        ("ulmg", "0014_auto_20181006_2159"),
        ("ulmg", "0015_auto_20181007_1222"),
        ("ulmg", "0016_player_fg_fv"),
        ("ulmg", "0017_auto_20181008_1936"),
        ("ulmg", "0018_auto_20181008_1945"),
        ("ulmg", "0019_player_ba_prospect_rank"),
        ("ulmg", "0020_auto_20181009_1827"),
        ("ulmg", "0021_player_mlb_prospect_rank"),
        ("ulmg", "0022_auto_20181010_1501"),
        ("ulmg", "0023_auto_20181010_1518"),
        ("ulmg", "0024_player_is_rostered"),
        ("ulmg", "0025_auto_20181014_1150"),
        ("ulmg", "0026_auto_20181015_2117"),
        ("ulmg", "0027_auto_20181016_1505"),
        ("ulmg", "0028_auto_20181016_1621"),
        ("ulmg", "0029_auto_20181016_1632"),
        ("ulmg", "0030_auto_20181017_1329"),
        ("ulmg", "0031_player_notes"),
        ("ulmg", "0032_auto_20181017_1817"),
        ("ulmg", "0033_auto_20181018_1341"),
        ("ulmg", "0034_player_level_order"),
        ("ulmg", "0035_auto_20181020_0743"),
        ("ulmg", "0036_player_usage"),
        ("ulmg", "0037_draftpick_trade_tradereceipt"),
        ("ulmg", "0038_auto_20181023_1815"),
        ("ulmg", "0039_auto_20181031_1307"),
        ("ulmg", "0040_auto_20181031_1319"),
        ("ulmg", "0041_player_is_relief_eligible"),
        ("ulmg", "0042_player_steamer_predix"),
        ("ulmg", "0043_auto_20181110_1657"),
        ("ulmg", "0044_auto_20181110_1958"),
        ("ulmg", "0045_auto_20181111_1153"),
        ("ulmg", "0046_auto_20181111_2004"),
        ("ulmg", "0047_player_verified"),
        ("ulmg", "0048_draftpick_overall_pick_number"),
        ("ulmg", "0049_draftpick_slug"),
        ("ulmg", "0050_tradesummary"),
        ("ulmg", "0051_remove_tradesummary_teams"),
        ("ulmg", "0052_auto_20181123_2132"),
        ("ulmg", "0053_auto_20181123_2132"),
        ("ulmg", "0054_auto_20181123_2133"),
        ("ulmg", "0055_auto_20181123_2133"),
        ("ulmg", "0056_auto_20181123_2134"),
        ("ulmg", "0057_auto_20181124_1218"),
        ("ulmg", "0058_team_championships"),
        ("ulmg", "0059_auto_20181203_0912"),
        ("ulmg", "0060_auto_20181205_0820"),
        ("ulmg", "0061_trade_season"),
        ("ulmg", "0062_somrunsyear"),
        ("ulmg", "0063_auto_20181216_1349"),
        ("ulmg", "0064_scoutingreport"),
        ("ulmg", "0065_player_defense"),
        ("ulmg", "0066_auto_20190119_1243"),
        ("ulmg", "0067_auto_20190119_1256"),
        ("ulmg", "0068_scoutingreport_report"),
        ("ulmg", "0069_auto_20190209_1402"),
        ("ulmg", "0070_player_eta"),
        ("ulmg", "0071_player_is_interesting"),
        ("ulmg", "0072_remove_player_is_prospect"),
        ("ulmg", "0073_player_interest_order"),
        ("ulmg", "0074_player_bp_prospect_rank"),
        ("ulmg", "0075_player_js_prospect_rank"),
        ("ulmg", "0076_livestat"),
        ("ulmg", "0077_auto_20190610_1854"),
        ("ulmg", "0078_auto_20190611_1744"),
        ("ulmg", "0079_auto_20190611_2022"),
        ("ulmg", "0080_auto_20190612_1550"),
        ("ulmg", "0081_auto_20190619_2013"),
        ("ulmg", "0082_auto_20190619_2038"),
        ("ulmg", "0083_auto_20190624_1358"),
        ("ulmg", "0084_player_ls_is_mlb"),
        ("ulmg", "0085_auto_20190730_1502"),
        ("ulmg", "0086_player_bref_img"),
        ("ulmg", "0087_auto_20190905_1138"),
        ("ulmg", "0088_auto_20191027_1050"),
        ("ulmg", "0089_auto_20191228_1527"),
        ("ulmg", "0090_auto_20191228_1535"),
        ("ulmg", "0091_auto_20191228_1541"),
        ("ulmg", "0092_auto_20191228_1554"),
        ("ulmg", "0093_auto_20200105_0838"),
        ("ulmg", "0094_auto_20200105_1105"),
        ("ulmg", "0095_auto_20200120_1954"),
        ("ulmg", "0096_auto_20200120_1955"),
        ("ulmg", "0097_auto_20200120_1955"),
        ("ulmg", "0098_auto_20200216_1714"),
        ("ulmg", "0099_auto_20200218_2043"),
        ("ulmg", "0100_auto_20200218_2048"),
        ("ulmg", "0101_auto_20200218_2108"),
        ("ulmg", "0102_auto_20200218_2109"),
        ("ulmg", "0103_auto_20200218_2115"),
        ("ulmg", "0104_player_b_rk"),
        ("ulmg", "0105_player_b_kl"),
        ("ulmg", "0106_player_b_avg"),
        ("ulmg", "0105_player_b_grp"),
        ("ulmg", "0107_merge_20200310_1057"),
        ("ulmg", "0108_auto_20200325_0841"),
        ("ulmg", "0109_auto_20200703_1319"),
        ("ulmg", "0110_player_birthdate_qa"),
        ("ulmg", "0111_draftpick_skipped"),
        ("ulmg", "0112_player_is_protected"),
        ("ulmg", "0113_auto_20200724_0727"),
        ("ulmg", "0114_auto_20200724_0739"),
        ("ulmg", "0115_auto_20200725_0858"),
        ("ulmg", "0116_player_is_bullpen"),
        ("ulmg", "0117_auto_20200726_1428"),
        ("ulmg", "0118_auto_20200726_1528"),
        ("ulmg", "0119_auto_20200726_1530"),
        ("ulmg", "0120_auto_20200727_1337"),
        ("ulmg", "0121_auto_20200727_1405"),
        ("ulmg", "0122_auto_20200727_1416"),
        ("ulmg", "0123_team_ls_ab"),
        ("ulmg", "0124_auto_20200727_1428"),
        ("ulmg", "0125_auto_20200727_1445"),
        ("ulmg", "0126_player_ls_er"),
        ("ulmg", "0127_auto_20200727_1538"),
        ("ulmg", "0128_team_ls_whip"),
        ("ulmg", "0129_team_ls_hits_9"),
        ("ulmg", "0130_delete_somrunsyear"),
        ("ulmg", "0131_transaction"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("city", models.CharField(max_length=255)),
                ("nickname", models.CharField(max_length=255)),
                ("division", models.CharField(blank=True, max_length=255, null=True)),
                ("abbreviation", models.CharField(max_length=3)),
                ("owner", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "owner_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "championships",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=4),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "ls_avg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("ls_bb", models.IntegerField(blank=True, null=True)),
                (
                    "ls_bb_9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_bb_pct",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("ls_2b", models.IntegerField(blank=True, null=True)),
                ("ls_er", models.IntegerField(blank=True, null=True)),
                (
                    "ls_era",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("ls_g", models.IntegerField(blank=True, null=True)),
                ("ls_gs", models.IntegerField(blank=True, null=True)),
                ("ls_ha", models.IntegerField(blank=True, null=True)),
                ("ls_hits", models.IntegerField(blank=True, null=True)),
                ("ls_hr", models.IntegerField(blank=True, null=True)),
                (
                    "ls_hr_9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("ls_hra", models.IntegerField(blank=True, null=True)),
                (
                    "ls_ip",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_iso",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("ls_k", models.IntegerField(blank=True, null=True)),
                (
                    "ls_k_9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_k_pct",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_obp",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("ls_plate_appearances", models.IntegerField(blank=True, null=True)),
                ("ls_rbi", models.IntegerField(blank=True, null=True)),
                ("ls_runs", models.IntegerField(blank=True, null=True)),
                ("ls_sb", models.IntegerField(blank=True, null=True)),
                (
                    "ls_slg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("ls_3b", models.IntegerField(blank=True, null=True)),
                ("ls_pbb", models.IntegerField(blank=True, null=True)),
                ("ls_pk", models.IntegerField(blank=True, null=True)),
                ("ls_ab", models.IntegerField(blank=True, null=True)),
                (
                    "ls_whip",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "ls_hits_9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
            ],
            options={"abstract": False, "ordering": ["abbreviation"],},
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("fg_id", models.CharField(blank=True, max_length=255, null=True)),
                ("fg_url", models.CharField(blank=True, max_length=255, null=True)),
                ("bref_id", models.CharField(blank=True, max_length=255, null=True)),
                ("bref_url", models.CharField(blank=True, max_length=255, null=True)),
                ("is_owned", models.BooleanField(default=False)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ulmg.Team",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("V", "V"), ("A", "A"), ("B", "B")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("P", "Pitcher"),
                            ("C", "Catcher"),
                            ("IF", "Infield"),
                            ("OF", "Outfield"),
                            ("IF-OF", "Infield/Outfield"),
                            ("OF-P", "Pitcher/Outfield"),
                            ("IF-P", "Pitcher/Infield"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("ba_id", models.CharField(blank=True, max_length=255, null=True)),
                ("ba_url", models.CharField(blank=True, max_length=255, null=True)),
                ("is_carded", models.BooleanField(default=False)),
                ("is_aaa_roster", models.BooleanField(default=False)),
                ("is_amateur", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_mlb_roster", models.BooleanField(default=False)),
                ("is_1h_c", models.BooleanField(default=False)),
                ("is_1h_p", models.BooleanField(default=False)),
                ("is_1h_pos", models.BooleanField(default=False)),
                ("is_35man_roster", models.BooleanField(default=False)),
                ("is_reserve", models.BooleanField(default=False)),
                ("level_order", models.IntegerField(blank=True, null=True)),
                ("cs_gp", models.IntegerField(blank=True, null=True)),
                ("bp_id", models.CharField(blank=True, max_length=255, null=True)),
                ("mlbam_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cs_ip",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "defense",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("is_2h_draft", models.BooleanField(default=False)),
                (
                    "ls_avg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_babip",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_bb_9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_bb_pct",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_era",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "ls_fip",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("ls_g", models.IntegerField(blank=True, null=True)),
                (
                    "ls_gb_pct",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("ls_gs", models.IntegerField(blank=True, null=True)),
                ("ls_hr", models.IntegerField(blank=True, null=True)),
                (
                    "ls_hr_9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_hr_fb",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_ip",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_iso",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_k_9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_k_pct",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_lob_pct",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_obp",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("ls_plate_appearances", models.IntegerField(blank=True, null=True)),
                ("ls_sb", models.IntegerField(blank=True, null=True)),
                (
                    "ls_siera",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "ls_slg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "ls_woba",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("ls_wrc_plus", models.IntegerField(blank=True, null=True)),
                (
                    "ls_xfip",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "ls_xavg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "ls_xavg_diff",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "ls_xslg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "ls_xslg_diff",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "ls_xwoba",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "ls_xwoba_diff",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                ("ls_is_mlb", models.BooleanField(default=False)),
                ("bref_img", models.CharField(blank=True, max_length=255, null=True)),
                ("ls_rbi", models.IntegerField(blank=True, null=True)),
                ("ls_runs", models.IntegerField(blank=True, null=True)),
                ("cs_pa", models.IntegerField(blank=True, null=True)),
                ("cs_st", models.IntegerField(blank=True, null=True)),
                (
                    "league",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NCAA", "NCAA"),
                            ("US HS", "US HS"),
                            ("JPN", "JPN"),
                            ("KOR", "KOR"),
                            ("J2", "J2"),
                            ("TAI", "TAI"),
                            ("MEX", "MEX"),
                            ("OTH", "OTH"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("mlb_dotcom", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mlb_dotcom_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ps_avg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("ps_bb", models.IntegerField(blank=True, null=True)),
                (
                    "ps_bb_9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "ps_bsr",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("ps_cs", models.IntegerField(blank=True, null=True)),
                (
                    "ps_def",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("ps_er", models.IntegerField(blank=True, null=True)),
                (
                    "ps_era",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "ps_fip",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "ps_fld",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("ps_g", models.IntegerField(blank=True, null=True)),
                ("ps_gs", models.IntegerField(blank=True, null=True)),
                ("ps_h", models.IntegerField(blank=True, null=True)),
                ("ps_hr", models.IntegerField(blank=True, null=True)),
                ("ps_ip", models.IntegerField(blank=True, null=True)),
                ("ps_is_mlb", models.BooleanField(default=False)),
                ("ps_k", models.IntegerField(blank=True, null=True)),
                (
                    "ps_k_9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "ps_obp",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "ps_off",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "ps_ops",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("ps_pa", models.IntegerField(blank=True, null=True)),
                (
                    "ps_ra9_war",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("ps_sb", models.IntegerField(blank=True, null=True)),
                (
                    "ps_slg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("ps_so", models.IntegerField(blank=True, null=True)),
                (
                    "ps_stat_origin",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ps_sv", models.IntegerField(blank=True, null=True)),
                (
                    "ps_war",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "ps_whip",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "ps_woba",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("ps_wrc_plus", models.IntegerField(blank=True, null=True)),
                ("fantrax_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "fantrax_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "raal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "raar",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "raat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "scouting_reports",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, null=True),
                        default=list,
                        size=None,
                    ),
                ),
                ("b_important", models.BooleanField(default=False)),
                ("b_info", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "b_interest",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("b_ba", models.IntegerField(blank=True, default=None, null=True)),
                ("b_bp", models.IntegerField(blank=True, default=None, null=True)),
                ("b_fg", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "b_fv",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("b_mlb", models.IntegerField(blank=True, default=None, null=True)),
                ("b_p365", models.IntegerField(blank=True, default=None, null=True)),
                ("b_pl", models.IntegerField(blank=True, default=None, null=True)),
                ("b_sckls", models.IntegerField(blank=True, default=None, null=True)),
                ("b_zips", models.IntegerField(blank=True, default=None, null=True)),
                ("b_rk", models.IntegerField(blank=True, default=None, null=True)),
                ("b_kl", models.IntegerField(blank=True, default=None, null=True)),
                ("b_avg", models.IntegerField(blank=True, default=None, null=True)),
                ("b_grp", models.IntegerField(blank=True, default=None, null=True)),
                ("is_2h_c", models.BooleanField(default=False)),
                ("is_2h_p", models.BooleanField(default=False)),
                ("is_2h_pos", models.BooleanField(default=False)),
                ("birthdate_qa", models.BooleanField(default=False)),
                ("is_protected", models.BooleanField(default=False)),
                ("injury_description", models.CharField(max_length=255, null=True)),
                ("is_bench", models.BooleanField(default=False)),
                ("is_injured", models.BooleanField(default=False)),
                ("is_mlb40man", models.BooleanField(default=False)),
                ("is_player_pool", models.BooleanField(default=False)),
                ("is_starter", models.BooleanField(default=False)),
                ("mlb_team", models.CharField(max_length=255, null=True)),
                ("mlb_team_abbr", models.CharField(max_length=255, null=True)),
                ("role", models.CharField(max_length=255, null=True)),
                ("is_bullpen", models.BooleanField(default=False)),
                ("rt_ab", models.IntegerField(blank=True, null=True)),
                ("rt_bb", models.IntegerField(blank=True, null=True)),
                ("rt_doubles", models.IntegerField(blank=True, null=True)),
                ("rt_h", models.IntegerField(blank=True, null=True)),
                ("rt_hr", models.IntegerField(blank=True, null=True)),
                ("rt_k", models.IntegerField(blank=True, null=True)),
                ("rt_r", models.IntegerField(blank=True, null=True)),
                ("rt_rbi", models.IntegerField(blank=True, null=True)),
                ("rt_sb", models.IntegerField(blank=True, null=True)),
                ("rt_triples", models.IntegerField(blank=True, null=True)),
                ("rt_er", models.IntegerField(blank=True, null=True)),
                ("rt_ip", models.CharField(blank=True, max_length=255, null=True)),
                ("rt_p", models.IntegerField(blank=True, null=True)),
                ("rt_pbb", models.IntegerField(blank=True, null=True)),
                ("rt_ph", models.IntegerField(blank=True, null=True)),
                ("rt_phr", models.IntegerField(blank=True, null=True)),
                ("rt_pk", models.IntegerField(blank=True, null=True)),
                ("rt_pr", models.IntegerField(blank=True, null=True)),
                ("rt_s", models.IntegerField(blank=True, null=True)),
                ("ls_bb", models.IntegerField(blank=True, null=True)),
                ("ls_2b", models.IntegerField(blank=True, null=True)),
                ("ls_ha", models.IntegerField(blank=True, null=True)),
                ("ls_hits", models.IntegerField(blank=True, null=True)),
                ("ls_hra", models.IntegerField(blank=True, null=True)),
                ("ls_k", models.IntegerField(blank=True, null=True)),
                ("ls_3b", models.IntegerField(blank=True, null=True)),
                ("ls_ab", models.IntegerField(blank=True, null=True)),
                ("ls_pbb", models.IntegerField(blank=True, null=True)),
                ("ls_pk", models.IntegerField(blank=True, null=True)),
                ("ls_er", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
                "ordering": ["last_name", "first_name", "level", "position"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("date", models.DateField()),
                ("season", models.IntegerField(blank=True, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="DraftPick",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("year", models.CharField(max_length=4)),
                ("pick_number", models.IntegerField(blank=True, null=True)),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("offseason", "offseason"),
                            ("midseason", "midseason"),
                        ],
                        max_length=255,
                    ),
                ),
                ("team_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "player_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pick_notes", models.TextField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ulmg.Player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team",
                        to="ulmg.Team",
                    ),
                ),
                ("draft_round", models.IntegerField(null=True)),
                (
                    "draft_type",
                    models.CharField(
                        choices=[
                            ("aa", "aa"),
                            ("open", "open"),
                            ("balance", "balance"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "original_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="original_team",
                        to="ulmg.Team",
                    ),
                ),
                ("overall_pick_number", models.IntegerField(blank=True, null=True)),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                ("skipped", models.BooleanField(default=False)),
            ],
            options={
                "ordering": [
                    "-year",
                    "-season",
                    "draft_type",
                    "draft_round",
                    "pick_number",
                ],
            },
        ),
        migrations.CreateModel(
            name="TradeSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("season", models.CharField(blank=True, max_length=255, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[
                            ("players only", "players only"),
                            ("players and picks", "players and picks"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={"abstract": False, "ordering": ["-season", "trade_type"],},
        ),
        migrations.CreateModel(
            name="TradeReceipt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "trade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ulmg.Trade",
                    ),
                ),
                (
                    "picks",
                    models.ManyToManyField(
                        blank=True, related_name="picks", to="ulmg.DraftPick"
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True, related_name="players", to="ulmg.Player"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ulmg.Team",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ScoutingReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("player_name", models.CharField(blank=True, max_length=255)),
                ("season", models.IntegerField()),
                ("date", models.DateField()),
                ("pv", models.CharField(blank=True, max_length=5, null=True)),
                ("fv", models.CharField(blank=True, max_length=5, null=True)),
                ("risk", models.IntegerField(blank=True, null=True)),
                ("risk_name", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("evaluator", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "report_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("level", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ulmg.Player",
                    ),
                ),
                ("report", models.TextField(blank=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("drafted", "drafted"),
                            ("dropped", "dropped"),
                            ("traded", "traded"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "player_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("season", models.IntegerField()),
                ("date", models.DateField(auto_now=True)),
                (
                    "destination_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_team",
                        to="ulmg.Team",
                    ),
                ),
                (
                    "origination_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origination_team",
                        to="ulmg.Team",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ulmg.Player",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
