# Generated by Django 3.0.7 on 2020-10-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0001_squashed_0131_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ls_ip',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
