# Generated by Django 3.0.7 on 2021-01-31 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0002_auto_20201014_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.CharField(max_length=4)),
                ('skew', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('med', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('avg', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('law', models.IntegerField(blank=True, null=True)),
                ('ba', models.IntegerField(blank=True, null=True)),
                ('bp', models.IntegerField(blank=True, null=True)),
                ('mlb', models.IntegerField(blank=True, null=True)),
                ('fg', models.IntegerField(blank=True, null=True)),
                ('p365', models.IntegerField(blank=True, null=True)),
                ('plive', models.IntegerField(blank=True, null=True)),
                ('p1500', models.IntegerField(blank=True, null=True)),
                ('ftrax', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ulmg.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
