# Generated by Django 3.0.7 on 2021-02-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0003_prospectrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectrating',
            name='rank_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
