# Generated by Django 3.0.7 on 2021-02-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0004_prospectrating_rank_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectrating',
            name='player_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
