# Generated by Django 2.0.2 on 2018-02-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0006_player_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playernote',
            options={'ordering': ['last_modified']},
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
