# Generated by Django 2.0.2 on 2018-02-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0008_auto_20180202_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('IF', 'Infield'), ('OF', 'Outfield'), ('UT', 'Utility'), ('DH', 'Hitter')], max_length=255, null=True),
        ),
    ]
