# Generated by Django 3.0.7 on 2021-02-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0010_team_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="owner_name",
        ),
        migrations.AddField(
            model_name="team",
            name="owner_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ulmg.Owner",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="owner",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
