# Generated by Django 2.0.2 on 2018-10-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0010_auto_20180202_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name', 'first_name', 'position']},
        ),
        migrations.AddField(
            model_name='player',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='mlb_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
