# Generated by Django 2.0.2 on 2018-10-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0011_auto_20181006_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='roster_conflict',
        ),
    ]
