# Generated by Django 3.0.7 on 2021-02-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0015_player_age_raw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='age_raw',
            new_name='raw_age',
        ),
    ]
