# Generated by Django 3.0.7 on 2021-02-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0018_player_fg_fv"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="eligible_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
