# Generated by Django 2.0.2 on 2018-10-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0018_auto_20181008_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ba_prospect_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
