# Generated by Django 2.0.2 on 2018-10-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0019_player_ba_prospect_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ba_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ba_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
