# Generated by Django 2.0.2 on 2018-10-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0020_auto_20181009_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mlb_prospect_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
