# Generated by Django 3.0.7 on 2021-02-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0020_auto_20210215_1325"),
    ]

    operations = [
        migrations.AddField(
            model_name="prospectrating",
            name="cbs",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
