# Generated by Django 3.0.7 on 2021-02-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0021_prospectrating_cbs"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="cannot_be_protected",
            field=models.BooleanField(default=False),
        ),
    ]
