# Generated by Django 3.1 on 2021-02-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0022_player_cannot_be_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='covid_protected',
            field=models.BooleanField(default=False),
        ),
    ]
