# Generated by Django 3.1 on 2021-02-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0023_player_covid_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fg_eta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
