# Generated by Django 2.0.2 on 2018-10-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0025_auto_20181014_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name', 'first_name', 'level', 'position']},
        ),
    ]
