# Generated by Django 3.1 on 2021-03-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0026_prospectrating_espn'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fg_org_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
