# Generated by Django 3.2.7 on 2021-11-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0028_auto_20210402_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
