# Generated by Django 2.0.8 on 2018-10-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0028_auto_20181016_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='field',
            new_name='division',
        ),
    ]
