# Generated by Django 3.2.7 on 2022-01-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0030_event_occurrence"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="chat_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
