# Generated by Django 2.0.8 on 2018-10-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0030_auto_20181017_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
