# Generated by Django 3.2.7 on 2022-01-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0031_auto_20220108_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('mlb_team', models.CharField(max_length=255)),
                ('first_year', models.IntegerField(blank=True, null=True)),
                ('stadium_blurb', models.TextField(blank=True, null=True)),
                ('stadium_img', models.CharField(blank=True, max_length=255, null=True)),
                ('park_factor', models.IntegerField(blank=True, null=True)),
                ('pf_wobacon', models.IntegerField(blank=True, null=True)),
                ('pf_bacon', models.IntegerField(blank=True, null=True)),
                ('pf_runs', models.IntegerField(blank=True, null=True)),
                ('pf_obp', models.IntegerField(blank=True, null=True)),
                ('pf_h', models.IntegerField(blank=True, null=True)),
                ('pf_1b', models.IntegerField(blank=True, null=True)),
                ('pf_2b', models.IntegerField(blank=True, null=True)),
                ('pf_3b', models.IntegerField(blank=True, null=True)),
                ('pf_hr', models.IntegerField(blank=True, null=True)),
                ('pf_bb', models.IntegerField(blank=True, null=True)),
                ('pf_so', models.IntegerField(blank=True, null=True)),
                ('pf_years', models.CharField(blank=True, max_length=255, null=True)),
                ('pf_pa', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ulmg.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
