# Generated by Django 2.0.8 on 2018-10-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0033_auto_20181018_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='level_order',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
