# Generated by Django 3.2.7 on 2022-01-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0033_auto_20220109_1409"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venue",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="player",
            name="strat_ratings",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
