# Generated by Django 2.0.8 on 2018-10-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0034_player_level_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='level_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
