# Generated by Django 2.0.8 on 2018-10-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0035_auto_20181020_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
