# Generated by Django 2.0.8 on 2018-10-23 13:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0036_player_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.CharField(max_length=4)),
                ('pick_number', models.IntegerField()),
                ('season', models.CharField(choices=[('offseason', 'offseason'), ('midseason', 'midseason')], max_length=255)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('player_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pick_notes', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ulmg.Player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ulmg.Team')),
            ],
            options={
                'ordering': ['year', '-season', '-pick_number'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('players_received', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('picks_received', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('receiving_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_team', to='ulmg.Team')),
                ('sending_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sending_team', to='ulmg.Team')),
                ('trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ulmg.Trade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
