# Generated by Django 3.2.11 on 2022-01-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0038_auto_20220122_2016"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="raal",
        ),
        migrations.RemoveField(
            model_name="player",
            name="raar",
        ),
        migrations.RemoveField(
            model_name="player",
            name="raat",
        ),
    ]
