# Generated by Django 3.2.11 on 2022-01-29 16:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0039_auto_20220123_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistplayer',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlistplayer',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
