# Generated by Django 2.0.8 on 2018-10-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0040_auto_20181031_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_relief_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
