# Generated by Django 3.2.11 on 2022-02-06 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0040_auto_20220129_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineupSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('position', models.CharField(choices=[('C', 'C'), ('1B', '1B'), ('2B', '2B'), ('3B', '3B'), ('SS', 'SS'), ('RF', 'RF'), ('CF', 'CF'), ('LF', 'LF'), ('DH', 'DH'), ('SP', 'SP'), ('RP', 'RP')], max_length=255, null=True)),
                ('plate_appearaces', models.IntegerField(blank=True, null=True)),
                ('starts', models.IntegerField(blank=True, null=True)),
                ('innings_pitched', models.IntegerField(blank=True, null=True)),
                ('strat_obtb_r', models.IntegerField(blank=True, null=True)),
                ('strat_obtb_l', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulmg.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('season', models.IntegerField()),
                ('slot_1b', models.ManyToManyField(blank=True, related_name='slot_1b', to='ulmg.LineupSlot')),
                ('slot_2b', models.ManyToManyField(blank=True, related_name='slot_2b', to='ulmg.LineupSlot')),
                ('slot_3b', models.ManyToManyField(blank=True, related_name='slot_3b', to='ulmg.LineupSlot')),
                ('slot_c', models.ManyToManyField(blank=True, related_name='slot_c', to='ulmg.LineupSlot')),
                ('slot_cf', models.ManyToManyField(blank=True, related_name='slot_cf', to='ulmg.LineupSlot')),
                ('slot_dh', models.ManyToManyField(blank=True, related_name='slot_dh', to='ulmg.LineupSlot')),
                ('slot_lf', models.ManyToManyField(blank=True, related_name='slot_lf', to='ulmg.LineupSlot')),
                ('slot_rf', models.ManyToManyField(blank=True, related_name='slot_rf', to='ulmg.LineupSlot')),
                ('slot_rp', models.ManyToManyField(blank=True, related_name='slot_rp', to='ulmg.LineupSlot')),
                ('slot_sp', models.ManyToManyField(blank=True, related_name='slot_sp', to='ulmg.LineupSlot')),
                ('slot_ss', models.ManyToManyField(blank=True, related_name='slot_ss', to='ulmg.LineupSlot')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ulmg.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
