# Generated by Django 2.0.8 on 2018-11-05 07:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0041_player_is_relief_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='steamer_predix',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
