# Generated by Django 3.2.11 on 2022-02-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0041_lineup_lineupslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineupslot',
            old_name='strat_obtb_l',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='lineupslot',
            old_name='strat_obtb_r',
            new_name='value_l',
        ),
        migrations.AddField(
            model_name='lineupslot',
            name='value_r',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
