# Generated by Django 3.2.18 on 2023-02-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0042_auto_20230222_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mlbam_checked',
            field=models.BooleanField(default=False),
        ),
    ]
