# Generated by Django 3.2.11 on 2022-02-06 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0042_auto_20220206_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineup',
            name='slot_1b',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='slot_2b',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='slot_3b',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='slot_c',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='slot_cf',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='slot_dh',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='slot_lf',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='slot_rf',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='slot_rp',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='slot_sp',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='slot_ss',
        ),
        migrations.AddField(
            model_name='lineupslot',
            name='lineup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ulmg.lineup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineupslot',
            name='relief_innings_pitched',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineupslot',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
