# Generated by Django 3.2.15 on 2023-09-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0043_player_mlbam_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='mlb_team',
            new_name='mlb_org',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='mlb_team_abbr',
            new_name='mlb_org_abbr',
        ),
        migrations.AddField(
            model_name='player',
            name='roster_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
