# Generated by Django 2.0.8 on 2018-11-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0043_auto_20181110_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpick',
            name='pick_number',
            field=models.IntegerField(null=True),
        ),
    ]
