# Generated by Django 3.2.15 on 2023-09-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0044_auto_20230907_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='baseballcube_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='perfectgame_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
