# Generated by Django 3.2.15 on 2023-09-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0045_auto_20230907_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='mlb_org_abbr',
        ),
        migrations.AddField(
            model_name='player',
            name='is_mlb',
            field=models.BooleanField(default=False),
        ),
    ]
