# Generated by Django 3.2.15 on 2023-09-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0046_auto_20230910_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
