# Generated by Django 2.0.8 on 2018-11-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0046_auto_20181111_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
