# Generated by Django 3.2.15 on 2023-10-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0047_player_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_trade_block',
            field=models.BooleanField(default=False),
        ),
    ]
