# Generated by Django 2.0.8 on 2018-11-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0047_player_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpick',
            name='overall_pick_number',
            field=models.IntegerField(null=True),
        ),
    ]
