# Generated by Django 5.0.1 on 2024-02-29 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0048_player_is_trade_block"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="is_mlb",
        ),
    ]
