# Generated by Django 2.0.8 on 2018-11-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0048_draftpick_overall_pick_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpick',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
