# Generated by Django 2.1.3 on 2018-11-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0049_draftpick_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('season', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('trade_type', models.CharField(choices=[('players only', 'players only'), ('players and picks', 'players and picks')], max_length=255)),
                ('teams', models.ManyToManyField(related_name='teams', to='ulmg.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
