# Generated by Django 5.0.1 on 2024-03-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0049_remove_player_is_mlb"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlistplayer",
            name="future_value",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
