# Generated by Django 2.1.3 on 2018-11-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0050_tradesummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradesummary',
            name='teams',
        ),
    ]
