# Generated by Django 5.1 on 2024-08-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0050_wishlistplayer_future_value"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tradereceipt",
            index=models.Index(
                fields=["trade", "team"], name="ulmg_trader_trade_i_7e5215_idx"
            ),
        ),
    ]
