# Generated by Django 5.1 on 2024-08-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0051_tradereceipt_ulmg_trader_trade_i_7e5215_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="draftpick",
            index=models.Index(fields=["team"], name="ulmg_draftp_team_id_3808f9_idx"),
        ),
    ]
