# Generated by Django 5.1 on 2024-11-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0052_draftpick_ulmg_draftp_team_id_3808f9_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="draftpick",
            name="ulmg_draftp_team_id_3808f9_idx",
        ),
        migrations.RemoveIndex(
            model_name="tradereceipt",
            name="ulmg_trader_trade_i_7e5215_idx",
        ),
        migrations.AddField(
            model_name="trade",
            name="teams",
            field=models.ManyToManyField(blank=True, null=True, to="ulmg.team"),
        ),
        migrations.AddField(
            model_name="trade",
            name="trade_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
