# Generated by Django 2.1.3 on 2018-11-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0052_auto_20181123_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='fangraphs_url',
            new_name='fg_url',
        ),
    ]
