# Generated by Django 5.1 on 2024-11-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0053_remove_draftpick_ulmg_draftp_team_id_3808f9_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="teams",
            field=models.ManyToManyField(blank=True, to="ulmg.team"),
        ),
    ]
