# Generated by Django 5.1 on 2024-11-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0054_alter_trade_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="trade_cache",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
