# Generated by Django 2.1.3 on 2018-11-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0054_auto_20181123_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='bbref_url',
            new_name='bref_url',
        ),
    ]
