# Generated by Django 5.1.4 on 2025-02-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0055_trade_trade_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlistplayer",
            name="player_fv",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wishlistplayer",
            name="player_level",
            field=models.CharField(
                choices=[
                    ("COL", "col"),
                    ("HS", "hs"),
                    ("MLB", "mlb"),
                    ("MINORS", "minors"),
                    ("NPB", "npb"),
                    ("KBO", "kbo"),
                    ("INT-AM", "int-am"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wishlistplayer",
            name="player_school",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wishlistplayer",
            name="player_type",
            field=models.CharField(
                choices=[("PRO", "pro"), ("AM", "am"), ("INT", "int")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wishlistplayer",
            name="player_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
