# Generated by Django 2.1.3 on 2018-11-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0056_auto_20181123_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_2h_c',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_2h_p',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_2h_pos',
        ),
    ]
