# Generated by Django 5.1.4 on 2025-02-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0056_wishlistplayer_player_fv_wishlistplayer_player_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlistplayer",
            name="player_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COL", "col"),
                    ("HS", "hs"),
                    ("MLB", "mlb"),
                    ("MINORS", "minors"),
                    ("NPB", "npb"),
                    ("KBO", "kbo"),
                    ("INT-AM", "int-am"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="wishlistplayer",
            name="player_type",
            field=models.CharField(
                blank=True,
                choices=[("PRO", "pro"), ("AM", "am"), ("INT", "int")],
                max_length=255,
                null=True,
            ),
        ),
    ]
