# Generated by Django 5.2 on 2025-04-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0057_alter_wishlistplayer_player_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerStatSeason",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("season", models.IntegerField(blank=True, null=True)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("1-majors", "1-majors"),
                            ("2-minors", "2-minors"),
                            ("3-npb", "3-npb"),
                            ("4-kbo", "4-kbo"),
                            ("5-ncaa", "5-ncaa"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("level", models.CharField(blank=True, max_length=255, null=True)),
                ("hit_stats", models.JSONField(blank=True, null=True)),
                ("pitch_stats", models.JSONField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ulmg.player",
                    ),
                ),
            ],
            options={
                "ordering": ["season", "classification"],
            },
        ),
    ]
