# Generated by Django 2.1.3 on 2018-11-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0058_team_championships'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fg_prospect_j2_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fg_prospect_risk',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
