# Generated by Django 2.0.8 on 2018-12-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0058_team_championships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradereceipt',
            name='picks',
            field=models.ManyToManyField(blank=True, null=True, related_name='picks', to='ulmg.DraftPick'),
        ),
        migrations.AlterField(
            model_name='tradereceipt',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, related_name='players', to='ulmg.Player'),
        ),
    ]
