# Generated by Django 5.2.3 on 2025-07-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0058_playerstatseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatseason',
            name='carded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='minors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='owned',
            field=models.BooleanField(default=False),
        ),
    ]
