# Generated by Django 5.2.3 on 2025-07-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0059_playerstatseason_carded_playerstatseason_minors_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season'], name='ulmg_player_season_b4cb82_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['minors'], name='ulmg_player_minors_bd2d49_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['owned'], name='ulmg_player_owned_a93699_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['carded'], name='ulmg_player_carded_f13293_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'minors'], name='ulmg_player_season_7f2dad_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'owned'], name='ulmg_player_season_fadb7b_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'minors', 'owned'], name='ulmg_player_season_9bca7b_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['player', 'season'], name='ulmg_player_player__b28d56_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['minors', 'owned', 'carded'], name='ulmg_player_minors_98eac8_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'classification'], name='ulmg_player_season_ee1458_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['classification'], name='ulmg_player_classif_e48fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['level'], name='ulmg_player_level_858e50_idx'),
        ),
    ]
