# Generated by Django 2.1.3 on 2018-11-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0059_auto_20181128_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutingReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('publication', models.CharField(choices=[('fg', 'Fangraphs'), ('ba', 'Baseball America'), ('sickels', 'John Sickels'), ('law', 'Keith Law'), ('mlb', 'MLB prospect pipeline'), ('2080', '2080 Baseball')], max_length=255)),
                ('pv', models.CharField(blank=True, max_length=3, null=True)),
                ('fv', models.CharField(blank=True, max_length=3, null=True)),
                ('risk', models.CharField(blank=True, choices=[('l', 'Low'), ('m', 'Moderate'), ('h', 'High'), ('e', 'Extreme')], max_length=1, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('rank_type', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ulmg.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
