# Generated by Django 2.1.3 on 2018-11-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0060_scoutingreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutingreport',
            name='risk',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Med', 'Moderate'), ('High', 'High'), ('Ext', 'Extreme')], max_length=1, null=True),
        ),
    ]
