# Generated by Django 5.2.3 on 2025-07-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0061_magiclinktoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='wishlistplayer',
            name='stats',
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='injury_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='is_35man_roster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='is_aaa_roster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='is_amateur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='is_bench',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='is_bullpen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='is_injured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='is_mlb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='is_mlb40man',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='is_mlb_roster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='is_player_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='is_starter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='mlb_org',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='role_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='roster_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
