# Generated by Django 2.1.3 on 2018-12-16 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0061_trade_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomRunsYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('season', models.IntegerField()),
                ('player_name', models.CharField(blank=True, max_length=255)),
                ('raar', models.DecimalField(decimal_places=1, max_digits=4)),
                ('raal', models.DecimalField(decimal_places=1, max_digits=4)),
                ('raat', models.DecimalField(decimal_places=1, max_digits=4)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ulmg.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
