# Generated by Django 2.1.3 on 2018-11-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0061_auto_20181128_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutingreport',
            name='eta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
