# Generated by Django 5.2.3 on 2025-07-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0062_remove_player_stats_remove_wishlistplayer_stats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='injury_description',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_35man_roster',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_aaa_roster',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_amateur',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_bench',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_bullpen',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_carded',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_injured',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_mlb40man',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_mlb_roster',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_player_pool',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_starter',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mlb_org',
        ),
        migrations.RemoveField(
            model_name='player',
            name='role',
        ),
        migrations.RemoveField(
            model_name='player',
            name='role_type',
        ),
        migrations.RemoveField(
            model_name='player',
            name='roster_status',
        ),
    ]
