# Generated by Django 2.1.3 on 2018-12-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0062_somrunsyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='raal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='raar',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='raat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
