# Generated by Django 5.2.3 on 2025-07-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0063_remove_player_injury_description_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'classification', 'owned'], name='ulmg_player_season_4ec766_idx'),
        ),
    ]
