# Generated by Django 5.2.3 on 2025-07-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0064_playerstatseason_ulmg_player_season_4ec766_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerstatseason',
            unique_together={('player', 'season', 'classification')},
        ),
    ]
