# Generated by Django 5.2.3 on 2025-07-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0065_alter_playerstatseason_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='draftpick',
            index=models.Index(fields=['team'], name='ulmg_draftp_team_id_3808f9_idx'),
        ),
        migrations.AddIndex(
            model_name='draftpick',
            index=models.Index(fields=['year', 'team'], name='ulmg_draftp_year_82041c_idx'),
        ),
        migrations.AddIndex(
            model_name='draftpick',
            index=models.Index(fields=['year', 'season', 'team'], name='ulmg_draftp_year_ae9f74_idx'),
        ),
        migrations.AddIndex(
            model_name='draftpick',
            index=models.Index(fields=['year', 'season', 'draft_type'], name='ulmg_draftp_year_ee77f3_idx'),
        ),
        migrations.AddIndex(
            model_name='draftpick',
            index=models.Index(fields=['player'], name='ulmg_draftp_player__0a4b70_idx'),
        ),
        migrations.AddIndex(
            model_name='draftpick',
            index=models.Index(fields=['overall_pick_number'], name='ulmg_draftp_overall_f47ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='draftpick',
            index=models.Index(fields=['year', 'season'], name='ulmg_draftp_year_43b2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='draftpick',
            index=models.Index(fields=['season', 'draft_type'], name='ulmg_draftp_season_3bf766_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team'], name='ulmg_player_team_id_dbdeef_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['name'], name='ulmg_player_name_917f06_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['last_name', 'first_name'], name='ulmg_player_last_na_fbc2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['level', 'position'], name='ulmg_player_level_18de89_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['position', 'level'], name='ulmg_player_positio_4bbc54_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_owned', 'team'], name='ulmg_player_is_owne_4f9839_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_owned', 'level'], name='ulmg_player_is_owne_94f408_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team', 'position'], name='ulmg_player_team_id_c887e3_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team', 'level', 'position'], name='ulmg_player_team_id_be239e_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_owned', 'level', 'is_reserve'], name='ulmg_player_is_owne_fd5f61_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'classification', 'owned', 'player'], name='ulmg_player_season_091188_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'owned', 'classification'], name='ulmg_player_season_cfead5_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['owned', 'season', 'classification'], name='ulmg_player_owned_0b1050_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['classification', 'season', 'owned'], name='ulmg_player_classif_2e67bf_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'player'], name='ulmg_player_season_9842d1_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'is_35man_roster'], name='ulmg_player_season_782325_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'is_mlb_roster'], name='ulmg_player_season_494047_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'owned', 'is_35man_roster'], name='ulmg_player_season_a18861_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistplayer',
            index=models.Index(fields=['wishlist'], name='ulmg_wishli_wishlis_66f2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistplayer',
            index=models.Index(fields=['wishlist', 'rank'], name='ulmg_wishli_wishlis_9779c9_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistplayer',
            index=models.Index(fields=['wishlist', 'player'], name='ulmg_wishli_wishlis_4d0184_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistplayer',
            index=models.Index(fields=['wishlist', 'player', 'rank'], name='ulmg_wishli_wishlis_d2b20d_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistplayer',
            index=models.Index(fields=['player'], name='ulmg_wishli_player__632f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistplayer',
            index=models.Index(fields=['rank'], name='ulmg_wishli_rank_e0d800_idx'),
        ),
    ]
