# Generated by Django 5.2.3 on 2025-07-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0066_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='player',
            name='ulmg_player_team_id_be239e_idx',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='ulmg_player_is_owne_fd5f61_idx',
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team', 'level'], name='ulmg_player_team_id_81c411_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['cannot_be_protected'], name='ulmg_player_cannot__044948_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['covid_protected'], name='ulmg_player_covid_p_1c3f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['mlbam_id'], name='ulmg_player_mlbam_i_7f1870_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['fg_id'], name='ulmg_player_fg_id_b1464f_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['fantrax_id'], name='ulmg_player_fantrax_1424f6_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_owned'], name='ulmg_player_is_owne_f27fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team'], include=('name', 'position', 'level'), name='idx_player_team_cov'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['name'], include=('team', 'position', 'level'), name='idx_player_name_cov'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['last_name', 'first_name'], include=('team', 'position', 'level'), name='idx_player_fname_cov'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(condition=models.Q(('level__in', ['V', 'A', 'B'])), fields=['team', 'position'], name='idx_upper_level_play'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(condition=models.Q(('level', 'V')), fields=['name'], name='idx_vet_players_name'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(condition=models.Q(('level', 'V')), fields=['position'], name='idx_vet_players_pos'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(condition=models.Q(('cannot_be_protected', True)), fields=['team'], name='idx_unprotectable_play'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(condition=models.Q(('covid_protected', True)), fields=['team'], name='idx_covid_protected_play'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(condition=models.Q(('is_trade_block', True)), fields=['is_trade_block'], name='idx_trade_block_play'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team', 'is_trade_block'], name='ulmg_player_team_id_66b324_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'classification', 'owned'], include=('player', 'carded', 'minors'), name='idx_pss_main_covering'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['player', 'season'], include=('classification', 'owned', 'carded'), name='idx_pss_player_covering'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(condition=models.Q(('owned', False)), fields=['season', 'classification'], name='idx_unowned_players'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(condition=models.Q(('carded', True)), fields=['season', 'classification'], name='idx_carded_players'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(condition=models.Q(('classification', '1-majors'), ('owned', False)), fields=['season'], name='idx_unowned_mlb'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(condition=models.Q(('hit_stats__isnull', False)), fields=['season', 'classification'], name='idx_hitters_with_stats'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(condition=models.Q(('pitch_stats__isnull', False)), fields=['season', 'classification'], name='idx_pitchers_with_stats'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'is_mlb_roster', 'is_aaa_roster'], name='ulmg_player_season_15c942_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'roster_status'], name='ulmg_player_season_b86b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'mlb_org'], name='ulmg_player_season_d12a67_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(condition=models.Q(('roster_status__startswith', 'IL-')), fields=['season'], name='idx_injured_players'),
        ),
    ]
