# Generated by Django 2.1.5 on 2019-01-19 12:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0066_auto_20190119_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='defense',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
    ]
