# Generated by Django 2.1.5 on 2019-02-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0067_auto_20190119_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutingreport',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
