# Generated by Django 5.2.3 on 2025-07-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0067_add_read_heavy_optimizations'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='playerstatseason',
            name='idx_unowned_mlb',
        ),
        migrations.AlterField(
            model_name='playerstatseason',
            name='classification',
            field=models.CharField(choices=[('1-mlb', '1-mlb'), ('2-milb', '2-milb'), ('3-npb', '3-npb'), ('4-kbo', '4-kbo'), ('5-college', '5-college')], max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(condition=models.Q(('classification', '1-mlb'), ('owned', False)), fields=['season'], name='idx_unowned_mlb'),
        ),
    ]
