# Generated by Django 2.1.5 on 2019-02-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0068_scoutingreport_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='klaw_prospect_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pl_prospect_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
