# Generated by Django 5.2.3 on 2025-07-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0068_remove_playerstatseason_idx_unowned_mlb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatseason',
            name='previous_carded',
            field=models.BooleanField(default=False),
        ),
    ]
