# Generated by Django 5.2.3 on 2025-07-06 11:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0069_playerstatseason_previous_carded'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='carded_seasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
