# Generated by Django 5.2.3 on 2025-07-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0070_player_carded_seasons'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='player',
            name='ulmg_player_cannot__044948_idx',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='ulmg_player_covid_p_1c3f1b_idx',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='idx_trade_block_play',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='ulmg_player_team_id_66b324_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerstatseason',
            name='ulmg_player_season_494047_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerstatseason',
            name='ulmg_player_season_15c942_idx',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_1h_c',
            new_name='is_ulmg_1h_c',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_1h_p',
            new_name='is_ulmg_1h_p',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_1h_pos',
            new_name='is_ulmg_1h_pos',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_2h_c',
            new_name='is_ulmg_2h_c',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_2h_draft',
            new_name='is_ulmg_2h_draft',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_2h_p',
            new_name='is_ulmg_2h_p',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_2h_pos',
            new_name='is_ulmg_2h_pos',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_protected',
            new_name='is_ulmg_protected',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_reserve',
            new_name='is_ulmg_reserve',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_trade_block',
            new_name='is_ulmg_trade_block',
        ),
        migrations.RenameField(
            model_name='playerstatseason',
            old_name='is_mlb_roster',
            new_name='is_ulmg_mlb_roster',
        ),
        migrations.RemoveField(
            model_name='player',
            name='cannot_be_protected',
        ),
        migrations.RemoveField(
            model_name='player',
            name='covid_protected',
        ),
        migrations.RemoveField(
            model_name='player',
            name='strat_ratings',
        ),
        migrations.AddField(
            model_name='player',
            name='is_ulmg_aaa_roster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(condition=models.Q(('is_ulmg_trade_block', True)), fields=['is_ulmg_trade_block'], name='idx_trade_block_play'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team', 'is_ulmg_trade_block'], name='ulmg_player_team_id_5fe4dd_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'is_ulmg_mlb_roster'], name='ulmg_player_season_021ece_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'is_ulmg_mlb_roster', 'is_aaa_roster'], name='ulmg_player_season_e86246_idx'),
        ),
    ]
