# Generated by Django 2.1.5 on 2019-02-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0070_player_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_interesting',
            field=models.BooleanField(default=False),
        ),
    ]
