# Generated by Django 5.2.3 on 2025-07-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0071_remove_player_ulmg_player_cannot__044948_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_ulmg_35man_roster',
            field=models.BooleanField(default=False),
        ),
    ]
