# Generated by Django 2.1.5 on 2019-02-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0071_player_is_interesting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_prospect',
        ),
    ]
