# Generated by Django 5.2.3 on 2025-07-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0072_player_is_ulmg_35man_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_ulmg_mlb_roster',
            field=models.BooleanField(default=False),
        ),
    ]
