# Generated by Django 2.1.5 on 2019-02-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0072_remove_player_is_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='interest_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
