# Generated by Django 2.1.5 on 2019-02-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0073_player_interest_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bp_prospect_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
