# Generated by Django 5.2.3 on 2025-07-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0073_player_is_ulmg_mlb_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_mlb_org',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
