# Generated by Django 5.2.3 on 2025-07-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0074_player_current_mlb_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_ulmg_midseason_unprotected',
            field=models.BooleanField(default=False),
        ),
    ]
