# Generated by Django 5.2.3 on 2025-07-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0076_playerstatseason_current_mlb_roster_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='playerstatseason',
            name='ulmg_player_season_782325_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerstatseason',
            name='ulmg_player_season_a18861_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerstatseason',
            name='ulmg_player_season_e86246_idx',
        ),
        migrations.RenameField(
            model_name='playerstatseason',
            old_name='is_35man_roster',
            new_name='is_ulmg35man_roster',
        ),
        migrations.RenameField(
            model_name='playerstatseason',
            old_name='is_aaa_roster',
            new_name='is_ulmg_aaa_roster',
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'is_ulmg35man_roster'], name='ulmg_player_season_7217ea_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'owned', 'is_ulmg35man_roster'], name='ulmg_player_season_09a1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['season', 'is_ulmg_mlb_roster', 'is_ulmg_aaa_roster'], name='ulmg_player_season_0eae50_idx'),
        ),
    ]
