# Generated by Django 5.2.1 on 2025-07-19 18:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0077_remove_playerstatseason_ulmg_player_season_782325_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="amateur_seasons",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="school",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
