# Generated by Django 5.2.1 on 2025-07-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0078_player_amateur_seasons_player_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="draft_year",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
