# Generated by Django 5.2.7 on 2025-10-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0079_player_draft_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatseason',
            name='is_career',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['is_career', 'classification'], name='ulmg_player_is_care_34e059_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatseason',
            index=models.Index(fields=['player', 'is_career'], name='ulmg_player_player__17ef3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='playerstatseason',
            constraint=models.UniqueConstraint(condition=models.Q(('is_career', True)), fields=('player', 'classification'), name='unique_career_pss_per_player_classification'),
        ),
    ]
