# Generated by Django 5.2.7 on 2025-01-XX XX:XX

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0080_playerstatseason_is_career_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatseason',
            name='defense',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
    ]
