# Generated by Django 5.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0081_playerstatseason_defense'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='strat_name',
            field=models.CharField(blank=True, help_text='Name as it appears in Strat-O-Matic files for matching', max_length=255, null=True),
        ),
    ]
