# Generated by Django 2.2.2 on 2019-06-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0081_auto_20190619_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ls_xavg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ls_xavg_diff',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ls_xslg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ls_xslg_diff',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ls_xwoba',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ls_xwoba_diff',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
