# Generated by Django 2.2.2 on 2019-07-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0083_auto_20190624_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ls_is_mlb',
            field=models.BooleanField(default=False),
        ),
    ]
