# Generated by Django 6.0.2 on 2026-02-15 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0083_add_duplicate_player_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicateplayercandidate',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_candidates_as_player1', to='ulmg.player'),
        ),
        migrations.AlterField(
            model_name='duplicateplayercandidate',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_candidates_as_player2', to='ulmg.player'),
        ),
    ]
