# Generated by Django 6.0.2 on 2026-03-15 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0084_duplicate_candidate_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpick',
            name='compensatory_for',
            field=models.ForeignKey(blank=True, help_text='If this is a compensatory pick, the pick that triggered it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensatory_picks', to='ulmg.draftpick'),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='losing_team',
            field=models.ForeignKey(blank=True, help_text='Team that lost the player (for compensatory pick)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draftpick_losing_team', to='ulmg.team'),
        ),
    ]
