# Generated by Django 6.0.2 on 2026-03-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0085_add_compensatory_pick_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftpick',
            name='compensatory_for',
        ),
        migrations.RemoveField(
            model_name='draftpick',
            name='losing_team',
        ),
    ]
