# Generated by Django 2.2.4 on 2019-08-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0085_auto_20190730_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bref_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
