# Generated by Django 5.2.3 on 2026-06-15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0086_remove_compensatory_pick_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstatseason",
            name="fg_positions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                blank=True,
                help_text="FanGraphs roster position1 tokens when Strat defense is unavailable",
                null=True,
                size=None,
            ),
        ),
    ]
