# Generated by Django 2.2.5 on 2019-10-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0087_auto_20190905_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='starts',
            new_name='cs_gp',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='raal',
            new_name='cs_ip',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bats',
        ),
        migrations.RemoveField(
            model_name='player',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='player',
            name='debut',
        ),
        migrations.RemoveField(
            model_name='player',
            name='draft_eligibility_year',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_relief_eligible',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mlbam_url',
        ),
        migrations.RemoveField(
            model_name='player',
            name='plate_appearances',
        ),
        migrations.RemoveField(
            model_name='player',
            name='raar',
        ),
        migrations.RemoveField(
            model_name='player',
            name='raat',
        ),
        migrations.RemoveField(
            model_name='player',
            name='relief_innings_pitched',
        ),
        migrations.RemoveField(
            model_name='player',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='player',
            name='steamer_predix',
        ),
        migrations.RemoveField(
            model_name='player',
            name='throws',
        ),
        migrations.RemoveField(
            model_name='player',
            name='verified',
        ),
        migrations.AddField(
            model_name='player',
            name='cs_pa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='cs_st',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
