# Generated by Django 5.2.3 on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0087_playerstatseason_fg_positions"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="bats",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="throws",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
