# Generated by Django 6.0.5 on 2026-09-25 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0088_player_bats_throws'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerAPIToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('token_prefix', models.CharField(db_index=True, max_length=16)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='ulmg.owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
