# Generated by Django 6.0.5 on 2026-09-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0089_owner_api_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstitutionCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('source_url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField()),
                ('content_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Constitution cache',
                'verbose_name_plural': 'Constitution cache',
                'ordering': ['-fetched_at', '-id'],
            },
        ),
    ]
