# Generated by Django 2.2.7 on 2020-01-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0093_auto_20200105_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ps_ip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
