# Generated by Django 3.0.2 on 2020-02-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0097_auto_20200120_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='b_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='b_info',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='b_interest',
            field=models.IntegerField(default=0),
        ),
    ]
