# Generated by Django 3.0.3 on 2020-02-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0100_auto_20200218_2048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player", name="b_ba", field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="player", name="b_bp", field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="player", name="b_fg", field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="player", name="b_mlb", field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="player", name="b_p365", field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="player", name="b_pl", field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="player",
            name="b_sckls",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="player", name="b_zips", field=models.IntegerField(default=None),
        ),
    ]
