# Generated by Django 3.0.3 on 2020-02-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0102_auto_20200218_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='b_info',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='b_interest',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
