# Generated by Django 3.0.3 on 2020-02-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0103_auto_20200218_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='b_rk',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
