# Generated by Django 3.0.3 on 2020-02-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0104_player_b_rk'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='b_kl',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
