# Generated by Django 3.0.3 on 2020-02-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0105_player_b_kl"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="b_avg",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
