# Generated by Django 3.0.3 on 2020-03-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0105_player_b_grp"),
        ("ulmg", "0106_player_b_avg"),
    ]

    operations = []
