# Generated by Django 3.0.7 on 2020-07-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0108_auto_20200325_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_2h_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_2h_p',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_2h_pos',
            field=models.BooleanField(default=False),
        ),
    ]
