# Generated by Django 3.0.7 on 2020-07-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0109_auto_20200703_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birthdate_qa',
            field=models.BooleanField(default=False),
        ),
    ]
