# Generated by Django 3.0.7 on 2020-07-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0110_player_birthdate_qa"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftpick",
            name="skipped",
            field=models.BooleanField(default=False),
        ),
    ]
