# Generated by Django 3.0.7 on 2020-07-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0111_draftpick_skipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_protected",
            field=models.BooleanField(default=False),
        ),
    ]
