# Generated by Django 3.0.7 on 2020-07-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0112_player_is_protected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="ls_bb_pct",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="ls_k_pct",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
    ]
