# Generated by Django 3.0.7 on 2020-07-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0114_auto_20200724_0739"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="injury_description",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="is_bench",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="is_injured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="is_mlb40man",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="is_player_pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="is_starter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="mlb_team",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="mlb_team_abbr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="role",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
