# Generated by Django 3.0.7 on 2020-07-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0115_auto_20200725_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_bullpen',
            field=models.BooleanField(default=False),
        ),
    ]
