# Generated by Django 3.0.7 on 2020-07-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0116_player_is_bullpen"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="rt_ab",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="rt_bb",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="rt_doubles",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="rt_h",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="rt_hr",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="rt_k",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="rt_r",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="rt_rbi",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="rt_sb",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="rt_triples",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
