# Generated by Django 3.0.7 on 2020-07-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0122_auto_20200727_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ls_ab',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
