# Generated by Django 3.0.7 on 2020-07-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0123_team_ls_ab"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player", old_name="ls_doubles", new_name="ls_2b",
        ),
        migrations.RenameField(
            model_name="player", old_name="ls_triples", new_name="ls_3b",
        ),
        migrations.AddField(
            model_name="player",
            name="ls_ab",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
