# Generated by Django 3.0.7 on 2020-07-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0124_auto_20200727_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ls_pbb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ls_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
