# Generated by Django 3.0.7 on 2020-07-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0125_auto_20200727_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ls_er',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
