# Generated by Django 3.0.7 on 2020-07-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0126_player_ls_er"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team", old_name="ls_doubles", new_name="ls_2b",
        ),
        migrations.RenameField(
            model_name="team", old_name="ls_triples", new_name="ls_3b",
        ),
    ]
