# Generated by Django 3.0.7 on 2020-07-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulmg", "0128_team_ls_whip"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="ls_hits_9",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
