# Generated by Django 3.0.7 on 2020-08-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulmg', '0130_delete_somrunsyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('transaction_type', models.CharField(choices=[('drafted', 'drafted'), ('dropped', 'dropped'), ('traded', 'traded')], max_length=255)),
                ('player_name', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('destination_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_team', to='ulmg.Team')),
                ('origination_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origination_team', to='ulmg.Team')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ulmg.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
